# config.yaml
datadir: "./lumina_data_node1"
port: 30303
debug: debug
enable_p2p: true
rpcport: 8545
rpcaddr: "0.0.0.0"
mining: true
miner: "0x50e8f7d870f4c22e00302c94a76a5cdf5f507961"
maxpeers: 100
chainid: 1
blockgaslimit: 10000000
cache: 512
handles: 512
verbosity: 2
enable_rate_limit: true
rate_limit: 1000
rate_limit_window: "1m"
enable_cache: true
cache_size: 10000
connection_timeout: "30s"
health_check_interval: "30s"
enable_metrics: false